# Generated by Django 4.2.2 on 2023-06-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=60)),
                ('email_add', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=60)),
                ('civil_status', models.CharField(max_length=60)),
                ('birth_date', models.CharField(max_length=60)),
                ('birth_legitimacy', models.IntegerField(choices=[(1, 'Legitimate'), (2, 'Illegitimate')], default=1)),
                ('birth_country', models.CharField(max_length=60)),
                ('birth_province', models.CharField(max_length=60)),
                ('birth_city', models.CharField(max_length=60)),
                ('father_last_name', models.CharField(max_length=60)),
                ('father_given_name', models.CharField(max_length=60)),
                ('father_citizenship', models.CharField(max_length=60)),
                ('mother_maiden_last_name', models.CharField(max_length=60)),
                ('mother_given_name', models.CharField(max_length=60)),
                ('mother_citizenship', models.CharField(max_length=60)),
                ('current_add', models.CharField(max_length=254)),
                ('current_province', models.CharField(max_length=60)),
                ('current_country', models.CharField(max_length=60)),
                ('occupation', models.CharField(max_length=60)),
                ('office_number', models.CharField(max_length=60, null=True)),
                ('office_add', models.CharField(max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Passport Applicant Profile',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.IntegerField(choices=[(1, 'Individual Appointment'), (2, 'Group Appointment')], default=1)),
                ('region', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('site', models.CharField(max_length=60)),
                ('office_name', models.CharField(max_length=100)),
                ('office_add', models.CharField(max_length=254)),
                ('contact_number', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Passport Application Appointment',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=60, null=True)),
                ('date_issue', models.CharField(blank=True, max_length=60, null=True)),
                ('issuing_auth', models.CharField(blank=True, max_length=100, null=True)),
                ('application_type', models.IntegerField(choices=[(1, 'New Application'), (2, 'Passport Renewal'), (3, 'Lost Passport')], default=1)),
                ('basis_of_citizenship', models.IntegerField(choices=[(1, 'PSA Birth Certificate'), (2, 'Identification Certificate of Election'), (3, 'PSA Marriage Certificate'), (4, 'Identification Certificate of Naturalization'), (5, 'Dual Citizenship Document'), (0, 'Others')], default=0)),
                ('has_foreign_passport', models.BooleanField(default=False)),
                ('emergency_contact_person', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=60)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_process.applicant')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport_process.appointment')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passport Application Processing',
            },
        ),
    ]
