# Generated by Django 4.2.2 on 2023-06-20 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passport_process', '0002_rename_has_foreign_passport_passport_foreign_passport_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=60)),
                ('email_address', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('present_address', models.CharField(max_length=254)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_passport_applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passport Applicant',
                'verbose_name_plural': 'Passport Applicant Details',
            },
        ),
        migrations.CreateModel(
            name='PassportAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.IntegerField(choices=[(1, 'Individual Appointment'), (2, 'Group Appointment')], default=1)),
                ('location_site', models.CharField(db_index=True, default=None, max_length=250)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_passport_appointment', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_passport_appointment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passport Appointment',
                'verbose_name_plural': 'Passport Application Appointment Schedule',
            },
        ),
        migrations.CreateModel(
            name='PassportProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_surname', models.CharField(db_index=True, default=None, max_length=100)),
                ('client_given_name', models.CharField(default=None, max_length=100)),
                ('client_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('passport_applicant_count', models.IntegerField(default=0)),
                ('epp_passport_name', models.CharField(blank=True, max_length=250, null=True)),
                ('epp_passport_number', models.CharField(blank=True, max_length=60, null=True)),
                ('date_issued', models.DateTimeField(blank=True, null=True)),
                ('passport_application_type', models.IntegerField(choices=[(1, 'New Application'), (2, 'Passport Renewal'), (3, 'Lost Passport')], default=1)),
                ('citizen_cert', models.IntegerField(choices=[(1, 'PSA Birth Certificate'), (2, 'Identification Certificate of Election'), (3, 'PSA Marriage Certificate'), (4, 'Identification Certificate of Naturalization'), (5, 'Dual Citizenship Document'), (0, 'Others')], default=0)),
                ('foreign_passport', models.BooleanField(default=False)),
                ('or_number', models.CharField(max_length=50)),
                ('or_receipt', models.ImageField(blank=True, default=None, upload_to='system/management/images/receipts/')),
                ('service_fee', models.DecimalField(decimal_places=2, default=None, max_digits=9)),
                ('passport_fee', models.DecimalField(decimal_places=2, default=None, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_passport_process', to=settings.AUTH_USER_MODEL)),
                ('passport_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_appointment', to='passport_process.passportappointment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_passport_process', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passport Process',
                'verbose_name_plural': 'Passport Application/Renewal Process',
            },
        ),
        migrations.RemoveField(
            model_name='passport',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
        migrations.AddField(
            model_name='passportapplicant',
            name='passport_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_process', to='passport_process.passportprocess'),
        ),
        migrations.AddField(
            model_name='passportapplicant',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_passport_applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
