# Generated by Django 4.2.2 on 2023-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('visa_processing_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_surname', models.CharField(db_index=True, max_length=250)),
                ('applicant_given_name', models.CharField(max_length=250)),
                ('applicant_passport_number', models.CharField(max_length=250)),
                ('applicant_sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default=None, max_length=10)),
                ('applicant_birthdate', models.DateField(max_length=10)),
                ('applicant_age', models.IntegerField()),
                ('visa_service_type', models.CharField(choices=[('New Application', 'NEW APPLICATION'), ('Renewal', 'RENEWAL')], default=None, max_length=25)),
                ('visa_status', models.CharField(choices=[('In-Progress', 'IN PROGRESS'), ('Completed', 'COMPLETED')], default=None, max_length=25)),
                ('visa_type', models.CharField(choices=[('Non Immigrant Visa', 'NON-IMMIGRANT VISA'), ('Immigrant', 'IMMIGRANT VISA')], default=None, max_length=25)),
                ('non_immigrant_visa_type', models.CharField(choices=[('N/A', 'None'), ('Business-Tourist Visa', 'Business Tourist Visa'), ('Work Visa', 'Work Visa'), ('Student Visa', 'Student Visa'), ('Exchange Visitor Visa', 'Exchange Visitor Visa'), ('Transit-Ship Crew Visa', 'Transit Ship Crew Visa'), ('Religious Worker Visa', 'Religious Worker Visa'), ('Domestic Employee Visa', 'Domestic Employee Visa'), ('Journalist-Media Visa', 'Journalist Media Visa'), ('Treaty Investors-Traders Visa', 'Treaty Investors Traders Visa'), ('CNMI Saipan Visa', 'Cnmi Saipan Visa'), ('NIV Type Visa', 'Niv Types Visa')], default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visa Processing',
            },
        ),
    ]
