# Generated by Django 4.2.2 on 2023-06-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visa',
            options={'verbose_name': 'Visa Processing', 'verbose_name_plural': 'Visa Processing'},
        ),
    ]
