# Generated by Django 4.2.2 on 2023-06-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0002_alter_visa_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='visa_service_type',
        ),
    ]
