# Generated by Django 4.2.2 on 2023-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0003_remove_visa_visa_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='visa_service_type',
            field=models.CharField(choices=[('New Application', 'NEW APPLICATION'), ('Renewal', 'RENEWAL')], default=None, max_length=25),
        ),
    ]
