# Generated by Django 4.2.2 on 2023-06-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa_processing', '0005_alter_visa_visa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='applicant_age',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='applicant_birthdate',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='applicant_passport_number',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='applicant_sex',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='non_immigrant_visa_type',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='visa_status',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='visa',
            name='appointment_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='visa',
            name='client_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='visa',
            name='client_given_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='visa',
            name='client_surname',
            field=models.CharField(db_index=True, default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='visa',
            name='country_visa',
            field=models.CharField(choices=[('none', 'Please Choose.'), ('usa', 'US'), ('canada', 'CANADA'), ('australia', 'AUSTRALIA'), ('japan', 'JAPAN'), ('korea', 'KOREA'), ('germany', 'GERMANY'), ('united_kingdom', 'UNITED KINGDOM')], default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='visa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create_visa_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visa',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='or_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='visa',
            name='or_receipt',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='visa',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'IN PROGRESS'), ('Deferred', 'DEFERRED'), ('Completed', 'COMPLETED')], default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='visa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_visa_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visa',
            name='visa_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='visa',
            name='visa_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visa',
            name='applicant_surname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_service_type',
            field=models.CharField(choices=[('New Application', 'NEW APPLICATION'), ('Renewal', 'RENEWAL')], max_length=25),
        ),
    ]
