# Generated by Django 4.2.2 on 2023-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0007_alter_visa_or_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='or_number',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
