# Generated by Django 4.2.2 on 2023-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0008_alter_visa_or_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='appointment_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
