# Generated by Django 4.2.2 on 2023-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0009_alter_visa_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
