# Generated by Django 4.2.2 on 2023-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_processing', '0011_alter_visa_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='or_number',
            field=models.CharField(max_length=50),
        ),
    ]
