# Generated by Django 4.2.2 on 2023-06-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='has_foreign_passport',
            new_name='foreign_passport_holder',
        ),
    ]
