# Generated by Django 4.2.2 on 2023-06-08 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eservices',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('services_name', models.CharField(db_index=True, max_length=250)),
                ('services_description', models.CharField(max_length=250)),
                ('services_date_created', models.DateTimeField(auto_now_add=True)),
                ('services_date_updated', models.DateTimeField(auto_now=True)),
                ('services_status', models.BooleanField(default=False)),
                ('services_slug', models.SlugField(max_length=250)),
                ('services_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('services_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
