# Generated by Django 4.2.2 on 2023-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eservices',
            name='services_href',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eservices',
            name='services_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eservices',
            name='services_slug',
            field=models.SlugField(),
        ),
    ]
